# Generated by Django 4.2.19 on 2025-02-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_text', models.CharField(max_length=200)),
                ('url_text', models.CharField(max_length=200)),
                ('description_text', models.CharField(max_length=200)),
                ('enabled_toggle', models.BooleanField()),
                ('tls_toggle', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_expires', models.CharField(max_length=200)),
                ('poll_date', models.DateTimeField(verbose_name='date polled')),
                ('status_code', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
